; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:olimex_e407]
platform = ststm32
board = olimex_e407
framework = stm32cube

; debuger config
upload_protocol = jlink
debug_tool = jlink
upload_speed = 12000
debug_speed = 12000


build_flags = 
    -D HSE_VALUE=12000000U
    -I src/hal         ; Tells compiler where your HAL headers are
    -I lib/SEGGER_RTT  ; TELLS COMPILER EXACTLY WHERE TO FIND SEGGER_RTT.h
    -I include
    -I lib/LwIP/src/include
    -I lib/LwIP/system
    -I lib/LwIP/src/include/netif
    -I lib/LwIP/src/include/lwip
    -I lib/LwIP/src/include/lwip/apps
    -I lib/LwIP/src/include/lwip/priv


    ; ==============================================================================
; SOURCE FILTER (Force PlatformIO to compile LwIP .c files from the lib/ folder)
; ==============================================================================
build_src_filter = 
    ; 1. Compile everything in the standard src/ folder (your main.cpp, etc.)
    +<*> 
    ; 2. Force compile LwIP Core
    +<../lib/LwIP/src/core/*.c>
    +<../lib/LwIP/src/core/ipv4/*.c>
    ; 3. Force compile LwIP Network Interfaces
    +<../lib/LwIP/src/netif/*.c>
    ; 4. Force compile LwIP API (Sockets, Netconn, etc.)
    +<../lib/LwIP/src/api/*.c>
    ; 5. Force compile LwIP Apps (MQTT, HTTP, etc. - if you need them)
    +<../lib/LwIP/src/apps/*/*.c>

lib_ldf_mode = deep+