#include "main.h"
#include "sys_debug.h"
#include "stm32f4xx_hal.h"
#include "app_motor.h"
#include "app_telemetry.h"
#include "app_encoder.h"
#include "app_switch.h"
#include "app_lamp.h"
#include "app_modbus.h"
#include "app_settings.h"
#include "lwip.h"      
#include "ethernetif.h"
#include <string.h>

#define ETH_RST_Pin         GPIO_PIN_6
#define ETH_RST_GPIO_Port   GPIOG

#define DEFAULT_BAUD        230400 // Default baud rate for UART telemetry (Can be overridden by settings loaded from Flash)
#define STARTUP_DELAY_MS    5000 //Requarment: After power-up, the system should wait for 5 seconds before accepting any commands.

// ==============================================================================
// FUNCTION PROTOTYPES
// ==============================================================================
void SystemClock_Config(void);
void Error_Handler(void);

// Externally defined Ethernet handle (Generated by CubeMX)
extern ETH_HandleTypeDef heth;


static bool lastSwitchState = false;            // Tracks the previous physical switch state
static bool sysMotorRunRequest = false;         // Unified control flag (True = Run, False = Stop)
static bool currentSwitchState = false;         // Current state of the physical switch (read each loop iteration)
static bool bStreamingState = false;            // Tracks whether the telemetry stream is currently active or not
static MotorState_t motorState = STATE_STOPPED; // Tracks the current state of the motor for telemetry purposes
static ModbusConfig_t   * mb ;                  // Global pointer to access Modbus configuration and command flags
static SystemSettings_t * mySettings;           // Global pointer to access system settings loaded from Flash
static SystemSettings_t   newCfg;               //  structure to hold new settings before saving to Flash

/**
 * @brief Configures the system clock for the STM32F407 to run at 168MHz using a 12MHz external crystal.
 * 
 * @note This function sets up the PLL and bus clocks for optimal performance.
 * No input parameters; modifies global clock settings. Calls Error_Handler() on failure.
 */
void SystemClock_Config(void) {
    RCC_OscInitTypeDef RCC_OscInitStruct = {0};
    RCC_ClkInitTypeDef RCC_ClkInitStruct = {0};

    // 1. Enable Power Control clock
    __HAL_RCC_PWR_CLK_ENABLE();
    __HAL_PWR_VOLTAGESCALING_CONFIG(PWR_REGULATOR_VOLTAGE_SCALE1);

    // 2. Configure HSE (High Speed External oscillator) and PLL
    // Olimex E407 has a 12MHz crystal. We multiply it to reach 168MHz.
    RCC_OscInitStruct.OscillatorType = RCC_OSCILLATORTYPE_HSE;
    RCC_OscInitStruct.HSEState = RCC_HSE_ON;
    RCC_OscInitStruct.PLL.PLLState = RCC_PLL_ON;
    RCC_OscInitStruct.PLL.PLLSource = RCC_PLLSOURCE_HSE;
    RCC_OscInitStruct.PLL.PLLM = 12;  // Divide 12MHz by 12 = 1MHz
    RCC_OscInitStruct.PLL.PLLN = 336; // Multiply 1MHz by 336 = 336MHz
    RCC_OscInitStruct.PLL.PLLP = RCC_PLLP_DIV2; // Divide 336MHz by 2 = 168MHz CPU Clock
    RCC_OscInitStruct.PLL.PLLQ = 7;   // USB Clock
    
    if (HAL_RCC_OscConfig(&RCC_OscInitStruct) != HAL_OK) {
        Error_Handler();
    }

    // 3. Configure CPU, AHB, and APB buses clocks
    RCC_ClkInitStruct.ClockType = RCC_CLOCKTYPE_HCLK | RCC_CLOCKTYPE_SYSCLK
                                | RCC_CLOCKTYPE_PCLK1 | RCC_CLOCKTYPE_PCLK2;
    RCC_ClkInitStruct.SYSCLKSource = RCC_SYSCLKSOURCE_PLLCLK;
    RCC_ClkInitStruct.AHBCLKDivider = RCC_SYSCLK_DIV1;       // 168 MHz
    RCC_ClkInitStruct.APB1CLKDivider = RCC_HCLK_DIV4;        // 42 MHz (Timers on APB1 will run at 84 MHz)
    RCC_ClkInitStruct.APB2CLKDivider = RCC_HCLK_DIV2;        // 84 MHz (Timers on APB2 will run at 168 MHz)

    if (HAL_RCC_ClockConfig(&RCC_ClkInitStruct, FLASH_LATENCY_5) != HAL_OK) {
        Error_Handler();
    }
}
/** 
* @brief Generated by CubeMX to initialize GPIOs. Make sure PG6 is configured as a standard output pin here for PHY reset control.
*/
static void MX_GPIO_Init(void)
{
  GPIO_InitTypeDef GPIO_InitStruct = {0};
  /* USER CODE BEGIN MX_GPIO_Init_1 */

  /* USER CODE END MX_GPIO_Init_1 */

  /* GPIO Ports Clock Enable */
  __HAL_RCC_GPIOH_CLK_ENABLE();
  __HAL_RCC_GPIOC_CLK_ENABLE();
  __HAL_RCC_GPIOA_CLK_ENABLE();
  __HAL_RCC_GPIOG_CLK_ENABLE();

  /*Configure GPIO pin Output Level */
  HAL_GPIO_WritePin(ETH_RST_GPIO_Port, ETH_RST_Pin, GPIO_PIN_RESET);

  /*Configure GPIO pin : ETH_RST_Pin */
  GPIO_InitStruct.Pin = ETH_RST_Pin;
  GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT_PP;
  GPIO_InitStruct.Pull = GPIO_NOPULL;
  GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
  HAL_GPIO_Init(ETH_RST_GPIO_Port, &GPIO_InitStruct);

  /* USER CODE BEGIN MX_GPIO_Init_2 */

  /* USER CODE END MX_GPIO_Init_2 */
}

/** 
*   @brief  Performs a hardware reset of the Ethernet PHY chip by toggling the reset GPIO pin.
*           This ensures the PHY starts in a known state before the MAC and LwIP stack initialize.
*   @note   Pull the reset line LOW to hold the PHY in reset state (PG6)
*/
static void PHY_Hardware_Reset(void) 
{
    HAL_GPIO_WritePin(GPIOG, GPIO_PIN_6, GPIO_PIN_RESET);   // Pull the reset line LOW to hold the PHY in reset state
    HAL_Delay(25);                                          // Wait for power and clocks to stabilize (min 15ms)
    HAL_GPIO_WritePin(GPIOG, GPIO_PIN_6, GPIO_PIN_SET);     // Release the reset line (Pull HIGH) to boot the PHY chip
    HAL_Delay(50);                                          // Wait for the PHY internal logic to initialize
}

/**
 * @brief Centralized NVIC priority configuration. 
 *        Overrides any priorities set by CubeMX or MSP Init functions.
 */
void App_NVIC_Reconfigure(void) {
    // 1. Z-Pulse (EXTI2) -> The "Master" of timing. No one can interrupt this.
    HAL_NVIC_SetPriority(EXTI2_IRQn, 0, 0); 
    
    // 2. Encoder Steps (EXTI9_5) -> High priority to avoid missing fast steps.
    HAL_NVIC_SetPriority(EXTI9_5_IRQn, 2, 0);

    // 3. Motor Control Timer (e.g., TIM3) -> Critical for frequency stability.
    // HAL_NVIC_SetPriority(TIM3_IRQn, 1, 0); 

    // 4. Telemetry UART (USART6) -> Important, but can wait a few cycles.
    HAL_NVIC_SetPriority(USART6_IRQn, 5, 0); 

    // 5. Ethernet (ETH) -> Heavy processing, moved to lower priority.
    HAL_NVIC_SetPriority(ETH_IRQn, 15, 0); 

    // 6. System Tick -> Moving to the lowest priority to stop it from 
    //    jittering our hardware interrupts.
    HAL_NVIC_SetPriority(SysTick_IRQn, 14, 0);
}

int main(void) 
{
    HAL_Init();                // Reset of all peripherals, Initializes the Flash interface and the Systick.
    SystemClock_Config();      // Configure the system clock to maximum performance (168 MHz)
    SEGGER_RTT_Init();         // Initialize SEGGER RTT for debugging output over JTAG (Non-blocking, zero-overhead when not in use)

    // Clear terminal screen (Terminal command \x1B[2J\x1B[H) and print boot info
    SEGGER_RTT_WriteString(0, "\x1B[2J\x1B[H"); 
    SEGGER_RTT_printf(0, "=== STM32F407 BARE METAL SYSTEM BOOT ===\n");
    SEGGER_RTT_printf(0, "System Clock: %u MHz\n", SystemCoreClock / 1000000);

    // ==========================================================================
    // LOAD SETTINGS FROM FLASH
    // ==========================================================================

    App_Settings_Init();                // Initialize settings module and load from Flash (or defaults if Flash is empty/corrupt)
    mySettings = App_Settings_Get();    // Get pointer to the active settings for easy access

    App_Motor_Init();
    App_Encoder_Init();
    App_Encoder_SetDirection(mySettings->encoderReversed);
    App_Switch_Init();
    App_Lamp_Init();                
    App_Telemetry_Init(mySettings->uartBaudRate);    
    MX_GPIO_Init();             // Initialize GPIOs (Make sure MX_GPIO_Init sets up PG6)
   
    HAL_Delay(STARTUP_DELAY_MS); // Requarment: After power-up, the system should wait for 5 seconds before accepting any commands.
    PHY_Hardware_Reset();        // Reset the PHY chip BEFORE initializing the network stack
    MX_LWIP_Init();              // Initialize the Ethernet MAC and LwIP Stack. // Read settings from Flash to configure IP address, subnet mask, gateway, and baud rate for telemetry UART.
    App_Modbus_Init();           // Initialize Modbus TCP Server
    
    // ==========================================================================
    // 3. SYNC MODBUS STATE WITH FLASH SETTINGS
    // ==========================================================================
    mb = App_Modbus_GetConfig();
    mb->targetRPM       = mySettings->targetRPM;
    mb->accelTimeSec    = mySettings->accelTimeSec;
    mb->motorDirection  = mySettings->motorDirection;
    mb->encoderReversed = mySettings->encoderReversed;
    mb->uartBaudRate    = mySettings->uartBaudRate;

    mb->autoStartStream = (mySettings->autoStartStream > 0);
    mb->pendingStreamStart = mb->autoStartStream;  
    mb->microsteps      = mySettings->microsteps;

    // Copy Network Params (This is what Python reads)
    memcpy(mb->ipAddress, mySettings->ipAddress, 4);
    memcpy(mb->netmask,   mySettings->netmask,   4);
    memcpy(mb->gateway,   mySettings->gateway,   4);  

   // FOR TEST 
    App_NVIC_Reconfigure();

    // ==========================================================================
    // THE INFINITE LOOP
    // ==========================================================================
    while (1) 
    {
        MX_LWIP_Process();                              // Process Network Traffic
        currentSwitchState = App_Switch_GetState();     // Read physical inputs and system state
        motorState = App_Motor_GetState();              // Get motor state

        // ======================================================================
        // PROCESS FLASH SAVE COMMAND
        // ======================================================================
        if (mb->pendingSaveCmd) 
        {
            mb->pendingSaveCmd = false;             // Acknowledge command
            // Populate a new structure with the current Modbus parameters
            newCfg.magicWord       = SETTINGS_MAGIC_WORD; // Set the magic word for validation
            newCfg.targetRPM       = mb->targetRPM;
            newCfg.accelTimeSec    = mb->accelTimeSec;
            newCfg.motorDirection  = mb->motorDirection;
            newCfg.encoderReversed = mb->encoderReversed;
            newCfg.uartBaudRate    = mb->uartBaudRate;
            newCfg.autoStartStream = mb->autoStartStream ? 1 : 0;  
            newCfg.microsteps      = mb->microsteps;
            //ip address, netmask, gateway are stored in the ModbusConfig_t struct but not yet in the Flash settings struct.
            memcpy(newCfg.ipAddress, mb->ipAddress, 4);
            memcpy(newCfg.netmask,   mb->netmask,   4);
            memcpy(newCfg.gateway,   mb->gateway,   4);
            App_Settings_Save(&newCfg); // Execute the Flash erase and write operations
        }

        mb = App_Modbus_GetConfig();

        // ======================================================================
        // CONTROL ARBITRATION (LOCAL VS REMOTE)
        // ======================================================================
        
        // A. Physical Switch Logic (Edge Detection)
        // The physical switch only overrides the system when its physical state CHANGES.
        if (currentSwitchState != lastSwitchState) {
            lastSwitchState = currentSwitchState;
            sysMotorRunRequest = currentSwitchState; // Switch dictates the new target state
            
            SEGGER_RTT_printf(0, "Hardware Switch: Motor %s Requested\n", 
                              sysMotorRunRequest ? "START" : "STOP");
        }

        if (mb->pendingMotorStart) {
            mb->pendingMotorStart = false; // Acknowledge command
            sysMotorRunRequest = true;
            SEGGER_RTT_WriteString(0, "Modbus: Motor START Requested\n");
        }
        if (mb->pendingMotorStop) {
            mb->pendingMotorStop = false; // Acknowledge command
            sysMotorRunRequest = false;
            SEGGER_RTT_WriteString(0, "Modbus: Motor STOP Requested\n");
        }
        if (mb->pendingStreamStart) {
            mb->pendingStreamStart = false;
            if (!mb->streamActive) {
                App_Telemetry_StartStream();
                mb->streamActive = true;
            }
        }
        if (mb->pendingStreamStop) {
            mb->pendingStreamStop = false;
            if (mb->streamActive) {
                App_Telemetry_StopStream();
                mb->streamActive = false;
            }
        }
        if (mb->pendingBaudChange) 
        {
            mb->pendingBaudChange = false; // Acknowledge command
            
            // Temporarily disable the telemetry stream if it's running
            bStreamingState = mb->streamActive;
            if ( bStreamingState == true) 
            {
                App_Telemetry_StopStream();
                // Insert your stop stream hardware logic here if necessary
            }
            App_Telemetry_SetBaudRate(mb->uartBaudRate);
            
            SEGGER_RTT_printf(0, "[SYSTEM] Telemetry UART Baud Rate updated to: %u bps\n", mb->uartBaudRate);
            
            // Resume streaming if it was active before the baud rate change
            if (bStreamingState ==true) 
            {
                 App_Telemetry_StartStream();
            }
        }
        if (mb->pendingEncoderDir) {
            mb->pendingEncoderDir = false;
            App_Encoder_SetDirection(mb->encoderReversed);
        }
        if (mb->pendingRebootCmd) 
        {
            mb->pendingRebootCmd = false; // Clear flag
            
            SEGGER_RTT_WriteString(0, "\n[SYSTEM] Reboot command received!\n");
            SEGGER_RTT_WriteString(0, "[SYSTEM] Flushing network buffers and restarting in 500ms...\n");
            
            // Wait 1000 milliseconds. 
            // This is CRITICAL! It gives the LwIP stack enough time to transmit 
            // the Modbus TCP response back to the Python GUI before the CPU dies.
            HAL_Delay(1000); 
            
            // Execute the hardware software-reset via ARM CMSIS
            NVIC_SystemReset(); 
        }

        // ======================================================================
        // MOTOR STATE MACHINE
        // ======================================================================
        switch (motorState) 
        {
            
            case STATE_STOPPED:
                App_Lamp_SetMode(0, LAMP_MODE_OFF); 
                
                // If a run is requested, apply current Modbus parameters and start
                if (sysMotorRunRequest == true) {
                    App_Motor_CalculateProfile(mb->targetRPM, mb->accelTimeSec, mb->microsteps);
                    App_Motor_Start(mb->motorDirection);
                }
                break;

            case STATE_ACCELERATING:
                App_Lamp_SetMode(0, LAMP_MODE_BLINK_FAST); 
                
                // If a stop is requested during acceleration, abort immediately
                if (sysMotorRunRequest == false) {
                    App_Motor_Stop(); 
                }
                break;

            case STATE_CRUISING:
                App_Lamp_SetMode(0, LAMP_MODE_ON); 
                
                // If a stop is requested during cruise, begin graceful deceleration
                if (sysMotorRunRequest == false) {
                    App_Motor_Stop(); 
                }
                break;

            case STATE_DECELERATING:
                App_Lamp_SetMode(0, LAMP_MODE_BLINK_FAST); 
                // Do nothing here. Let the kinematic engine finish the deceleration 
                // ramp to prevent mechanical jerk. It will transition to STOPPED automatically.
                break;

            default:
                App_Motor_Stop();
                break;
        }
    }
}

/**
 * @brief Error Handler function that gets called when a critical error occurs (e.g. clock configuration failure).
 */
void Error_Handler(void) {
    // Disable all interrupts and enter an infinite loop
    __disable_irq();
    while (1) { }
}
/**
 * @brief SysTick interrupt handler. 
 * @note This function is called every 1 ms by the SysTick timer. It increments the HAL tick count and also calls 
 *       our custom 1 ms tick functions for motor kinematics, switch debouncing, and lamp updates.
 */
void SysTick_Handler(void) {
    HAL_IncTick();
    App_Motor_KinematicTick_1ms(); // Call our custom motor kinematics function every 1 ms
    App_Switch_Tick_1ms();     // Call our custom switch debouncing function every 1 ms
    App_Lamp_Tick_1ms();       // Call our custom lamp update function every 1 ms
}
/**
 * @brief Ethernet interrupt handler. 
 * @note This function is called by the hardware when an Ethernet event occurs from the PHY (e.g. packet reception, transmission complete, error).
 */
void ETH_IRQHandler(void) {
    // Pass the hardware interrupt to the HAL driver
    HAL_ETH_IRQHandler(&heth);
}